### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by JohanNiklasson** [SteffeyDev/atemOSC#205]
Hi

Installed atemOSC (4.0.0), also installed OSCulator (3.4.3) and running ATEM software control (8.6).

Using an x-touch mini. Want to set the knobs to control dB in ATEM software control/ATEM mini pro ISO.

When starting atemOSC, the following error message appears:

("Could not create Switcher Discovery Instance.
ATEM Switcher Software may not be installed.")

![atemOSCerrormessage](https://user-images.githubusercontent.com/79338653/109293702-731b5f80-782c-11eb-825d-ce7a1b9174fa.jpg)

I can still enter Switcher IP address and after a few seconds, atemOSC discovers the Switcher but still lists is as Not Connected.

![atemOSC](https://user-images.githubusercontent.com/79338653/109293654-60a12600-782c-11eb-9b43-78f5bddd0f13.jpg)

From here, no matter what I do, atemOSC crashes.

Please advise.

Best Regards
Johan Niklasson

**Comment by SteffeyDev** [comment]
I haven't added support for 8.6 yet, latest version supported is 8.5.3. I'll mark this as a feature request and try to get that done for you soon.

**Comment by JohanNiklasson** [comment]
> I haven't added support for 8.6 yet, latest version supported is 8.5.3. I'll mark this as a feature request and try to get that done for you soon.

That would be awesome! Thank you for all your hard work.

Best Regards
Johan Niklasson

**Comment by ruebyi** [comment]
hmm, it's working flawless in my configuration with 8.6

Setup: ATEM Mini Pro + ATEM Studio HD + Oscualtor + ATEM OSC 4.0 on Mac OS HighSierra

**Comment by JohanNiklasson** [comment]
> hmm, it's working flawless in my configuration with 8.6
> 
> Setup: ATEM Mini Pro + ATEM Studio HD + Oscualtor + ATEM OSC 4.0 on Mac OS HighSierra

I use ATEM Mini Pro ISO, OSCulator, atemOSC on a MacBook Pro M1 running Big Sur. What is ATEM Studio HD?

Best Regards
Johan Niklasson

**Comment by JohanNiklasson** [comment]
> I haven't added support for 8.6 yet, latest version supported is 8.5.3. I'll mark this as a feature request and try to get that done for you soon.

Please let me know if there is anything you might need for this from me.

Best Regards
Johan Niklasson

**Comment by ruebyi** [comment]
> > What is ATEM Studio HD?
> 
> Best Regards
> Johan Niklasson

[https://www.blackmagicdesign.com/de/products/atemtelevisionstudio/](url)

**Comment by lewisjoss** [comment]
I’m also having the same issue on a Mac Mini M1 16gb. I’ve downgraded to 8.5.2 and it’s still throwing the error... I’m guessing it could be M1 related?

**Comment by SteffeyDev** [comment]
It might be M1 related, if it was it would be an issue with the ATEM SDK and thus out of my immediate control.

I just released v4.1.0 with 8.6 control, let me know if it works any better.

**Comment by lewisjoss** [comment]
This issue still persists unfortunately... it must be big sur/m1 related.

**Comment by SteffeyDev** [comment]
Probably M1 issue indeed, not much I can do immediately because atemOSC supports Big Sur M1, but the ATEM Switcher SDK might not.  I'll contact BlackMagicDesign to see if they can help

**Comment by joeallam** [comment]
Just adding in to say I too was having the same issue of "Could not create Switcher Discovery Instance.
ATEM Switcher Software may not be installed" followed by the app quitting, using the new ATEM Mini Extreme ISO on a new Mac mini M1 with ATEM Software Control 8.6

The quick fix for me was to locate AtemOSC in finder, File>Get Info>Open in Rosetta. It then opened correctly and worked as expected with the new hardware. Thanks for such a brilliant piece of software — hopefully these M1 issues can get ironed out easily, now that the new ATEMs have arrived.

**Comment by SteffeyDev** [comment]
I didn't know you could do that, very cool. I wonder if I only built atemOSC for Intel, if it would force it to use Rosetta and thus fix the issue, as a temp fix until BlackMagic updates their code for M1 (haven't heard back from them about it yet).

Either way, until I have time to test that, looks like a great work-around, thanks!

**Comment by JohanNiklasson** [comment]
> Just adding in to say I too was having the same issue of "Could not create Switcher Discovery Instance.
> ATEM Switcher Software may not be installed" followed by the app quitting, using the new ATEM Mini Extreme ISO on a new Mac mini M1 with ATEM Software Control 8.6
> 
> The quick fix for me was to locate AtemOSC in finder, File>Get Info>Open in Rosetta. It then opened correctly and worked as expected with the new hardware. Thanks for such a brilliant piece of software — hopefully these M1 issues can get ironed out easily, now that the new ATEMs have arrived.


Feeling stupid not having thought about that. A great workaround, thank you!

Best Regards
Johan Niklasson

**Comment by SteffeyDev** [comment]
Official response from BlackMagic:

> Thanks for contacting Blackmagic Developer support.

> ATEM Switchers 8.6 does not yet natively support Apple M1 Silicon.  Please continue to run your software with Rosetta on M1 silicon.

> Kind Regards

> Cameron Nichols

**Comment by SteffeyDev** [comment]
I'll probably un-support M1 in the next release until the SDK supports it, so that using Rosetta happens automatically.

**Comment by SteffeyDev** [comment]
Ok, I dropped M1 support in the latest release (4.1.4) which should force M1 macs to use Rosetta, thus "fixing" this issue.  This is the best I can do until BlackMagic adds M1 support to the SDK.

**Comment by SteffeyDev** [comment]
I haven't tested, please re-open if this "fix" doesn't work!

**Comment by SteffeyDev** [comment]
Good news! Just got an email from BlackMagic that ATEM Switchers update 8.6.4 includes support for M1 Macs.  That means I can turn off Rosetta, and you can get the full performance from atemOSC.

**Comment by SteffeyDev** [comment]
In talking with them, I discovered that if I add direct M1 support to atemOSC, atemOSC will only work if you have 8.6.4 installed on your switcher. So that I don't break backward compatibility, I'm going to hold off until potentially the next major release, since atemOSC does work on M1 macs now via Rosetta.

**Comment by SteffeyDev** [comment]
@randallpacker Does the current version work on you M1 Mac Mini?

**Comment by randallpacker** [comment]
I just installed and launched on my M1 running ATEM Software 8.6.4 and it connected and seems to be running fine.

**Comment by JFgith** [comment]
I have just installed ATEMosc on my new MacBookPro M1 (Monterey) and it works if I connect over ethernet and my router but it doesn't work if I only connect over USB. I have version 4.2.0. 
On my old MacBookPro 2015 with Mojave the connection works only with the USB cable.
Could you help?
Thanks a lot.

**Comment by SteffeyDev** [comment]
@JFgith  I've released a [new major version](https://github.com/SteffeyDev/atemOSC/releases/tag/v5.0.0), please test on that and open a support request at www.atemosc.com/support if there are still issues.
